name: beta-build

on:
  push:
    branches: [main]

jobs:
  flutter-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.24.0-10.2.pre'
          channel: 'dev'
  env-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Env Init
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > ./key.jks
